### ISSUE TITLE
Tags with dashes are not showing

### ISSUE THREAD

**Issue by srcr** [countercept/snake-skin#2]
Tags with dashes are not showing in the interface, for tagging CVE's this is very annoying.

**Comment by AlexKornitzer** [comment]
Ah right this will be due to the tag delimiters, this is an oversight that needs to be addressed. For now you should be able to remove it from the tag config and this will stop Snake Skin from stripping the CVE.
https://github.com/countercept/snake-skin/blob/master/src/config/tags.config.js

What is should probably do is ignore the delimiter if no match is found in the types dictionary.
